version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "80:80"

  backend:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "8080:8080"
