FROM python:3.10

WORKDIR /server

COPY server.py /server/
COPY games.py /server/
COPY games.db /server/
COPY requirements.txt /server/

RUN pip install -r /server/requirements.txt

EXPOSE 8080

CMD ["python3", "/server/server.py"]
